apiVersion: v1
kind: Service
metadata:
  name: rtp-ui
  labels:
    app: rtp-ui
    service: rtp-ui
  namespace: rtp-demo
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rtp-ui
