apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: rtp-infinispan
  namespace: rtp-data-grid
spec:
  replicas: 2
  service:
    type: Cache 
  autoscale:
    maxMemUsagePercent: 70 
    maxReplicas: 5 
    minMemUsagePercent: 30 
    minReplicas: 2 
  expose:
    type: Route 
  security:
    endpointSecretName: connect-secret
    endpointEncryption:
      type: None 
