apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: datagrid-operator
 namespace: rtp-demo
spec:
 channel: 8.1.x
 installPlanApproval: Automatic 
 name: datagrid
 source: redhat-operators
 sourceNamespace: openshift-marketplace
